name: hisabia_pos
description: Aplikasi POS Hisabia - mobile Flutter (backend Supabase sama dengan web).
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.8.0
  mobile_scanner: ^6.0.2
  intl: ^0.19.0
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
